import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import type { ReactNode } from 'react'
import './globals.css'
import Navbar from '../components/navigation/navbar'
import Footer from '@/components/footer'
import Providers from '@/components/providers'
import { Toaster } from '@/components/ui/toaster'

const urbanist = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${urbanist.className} antialiased`}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
